import { NextRequest } from "next/server";
import { DictionaryResponse } from "@/lib/types";

// Mock data for demonstration purposes
const mockDictionary: Record<string, DictionaryResponse> = {
  "hello": {
    word: "hello",
    phonetic: "/həˈloʊ/",
    definition: "is used as a greeting or to begin a conversation.",
    examples: [
      "Hello, how are you?",
      "She said hello to everyone in the room."
    ],
    synonyms: ["hi", "greetings", "salutations", "hey"],
    usage: "A friendly greeting used in informal and formal contexts."
  },
  "algorithm": {
    word: "algorithm",
    phonetic: "/ˈælɡəˌrɪðəm/",
    definition: "A process or set of rules to be followed in calculations or other problem-solving operations, especially by a computer.",
    examples: [
      "The search engine uses a complex algorithm to rank pages.",
      "Developers improved the algorithm to make the app run faster."
    ],
    synonyms: ["procedure", "process", "formula", "method"],
    usage: "Common in computing, mathematics, and increasingly in discussions about artificial intelligence and automated systems."
  },
  "serendipity": {
    word: "serendipity",
    phonetic: "/ˌsɛrənˈdɪpɪti/",
    definition: "The occurrence and development of events by chance in a happy or beneficial way.",
    examples: [
      "The discovery of penicillin was a moment of serendipity.",
      "Their meeting was pure serendipity."
    ],
    synonyms: ["chance", "fortune", "luck", "providence"],
    usage: "Often used to describe fortunate discoveries or events that happen by accident."
  }
};

export async function getDefinition(word: string): Promise<DictionaryResponse> {
  // Simulate API delay
  await new Promise(resolve => setTimeout(resolve, 800));
  
  const result = mockDictionary[word.toLowerCase()];
  
  if (result) {
    return result;
  }
  
  // Simulate a generated response for words not in our mock dictionary
  return {
    word: word,
    definition: `This is a simulated AI-generated definition for "${word}". In a real implementation, this would be generated by Gemini AI.`,
    examples: [`Here's an example sentence using "${word}".`],
    synonyms: ["similar1", "similar2"],
    usage: `The word "${word}" is typically used in specific contexts.`
  };
}